### ISSUE TITLE
Add notification & email？

### ISSUE THREAD

**Issue by littlegolden** [FriendsOfFlarum/moderator-notes#7]
Accepting notifications is a relatively important requirement. Actually use this period of time, I often miss the notes that created a few days ago.

**Comment by imorland** [comment]
Who would you want to send the notification to? I’m trying to understand the use case for this

**Comment by littlegolden** [comment]
When there is a new note, notify the recipient of the note

**Comment by littlegolden** [comment]
I went to check my note page today and I found that there were several notes sent to me a few days ago. If there has notifications, I can read theme in time.

**Comment by imorland** [comment]
Please remember that the moderator notes are not visible to the user they are placed against.

By default, only admins and moderators can view them, as this is the intended behaviour of the extension.

I’m more than happy to consider and implement additional features, just having difficulty understanding this at the moment

**Comment by littlegolden** [comment]
No wonder, my forum uses this extension as a message board. Every user can leave a message to others. 😂

**Comment by littlegolden** [comment]
Maybe different notifications can be used for different permissions:

If notes only visible to the admins, only the admins will be notified.
If visible to everyone, only the admins and the recipient of the note will be notified.

And every admins and note recipient can choose to turn the note notification on or off.

To avoid interruptions,  the note notification can be turned off by default.

**Comment by imorland** [comment]
> 
> 
> No wonder, my forum uses this extension as a message board. Every user can leave a message to others. 😂

That's not the intended functionality of this extension
